API:
  max_concurrent_requests: 100
  number_of_requests: 6
  endpoints:
    - endpoint: "http://localhost:3000/health"
      method: "POST"
      JSON: >
        {
          "Health": "health",
            "Really": {
             "Check": "test"
              }
         }
